### ISSUE TITLE
Send me an invitation

### ISSUE THREAD

**Issue by ViktoriaNeva** [levelupik/levelupik#1]
Hi! Send me an invitation, please. I want to test pre alpha

**Comment by levelupik** [comment]
Hi, @ViktoriaNeva !

Glad to see you in pre-alpha.

Here is your invitation code:
`Fk+dgVm9qlGn.3E9yFwGgclp.Q8Y@5fDN`

You can use it on https://finalem.levelupik.com

Our current developing page is https://finalem.levelupik.com/display
