### ISSUE TITLE
Is it feature? The same name of categories 

### ISSUE THREAD

**Issue by ViktoriaNeva** [levelupik/levelupik#10]
Is it ok that user can create categories with similar names?
![2020-05-20_22-25-24](https://user-images.githubusercontent.com/5111608/82489694-c1a40c80-9aea-11ea-8f2e-08583996e86a.png)

**Comment by levelupik** [comment]
Yes, totally.
With that, you can meet when trying to make two categories as separators, with the name '---------' - system will not try to stop you.
Or if you will meet words written the same but have a difference for you. 
"James while John had had had had had had had had had had had a better effect on the teacher"

**Comment by ViktoriaNeva** [comment]
Thank you for the answer
