### ISSUE TITLE
Does category can be without name?

### ISSUE THREAD

**Issue by ViktoriaNeva** [levelupik/levelupik#11]
![2020-05-20_22-39-59](https://user-images.githubusercontent.com/5111608/82489794-e1d3cb80-9aea-11ea-8c10-8adede297d92.png)

**Comment by levelupik** [comment]
Thank you, for this question.
Yes, it is.

You may want to make a name later, or it is some your personal stuff without a name, but only you know what exactly store there.
In this way, if someone will be behind you, and you would like to show him some of your notes, this category without a name will not cause anything in his thoughts.
A little bit of protection stuff.

**Comment by ViktoriaNeva** [comment]
Great! Thank you. This is amazing idea. I know what I will store in that kind of category
