### ISSUE TITLE
Active all button area 

### ISSUE THREAD

**Issue by ViktoriaNeva** [levelupik/levelupik#2]
To click on buttons - user should click on the image on the button

More comfortable - should be active for clicking all button area
![2020-05-14_23-24-18](https://user-images.githubusercontent.com/5111608/81983040-67630180-963b-11ea-8197-b40696086962.png)
![2020-05-14_23-25-07](https://user-images.githubusercontent.com/5111608/81983046-67fb9800-963b-11ea-9a5e-933d3eb8c426.png)

**Comment by levelupik** [comment]
Thank you, for your interest.

Good idea, it will be added to the next releases.

**Comment by ViktoriaNeva** [comment]
You are so generous and kind!
Great job

**Comment by levelupik** [comment]
@ViktoriaNeva The current clickable area of the top menu has been increased.
![2020-05-24_13-13-30](https://user-images.githubusercontent.com/58998177/82955273-27930700-9fb7-11ea-990d-6f8c818b80be.png)
to 
![2020-05-24_13-13-56](https://user-images.githubusercontent.com/58998177/82955282-2c57bb00-9fb7-11ea-9226-d578a3ead7f5.png)

Thank you for this issue.
