### ISSUE TITLE
Subcategories

### ISSUE THREAD

**Issue by ViktoriaNeva** [levelupik/levelupik#24]
Are you planning add subcategories? 
I am using LL and I really need subcategories

**Comment by levelupik** [comment]
Yeah, it is great functionality, and actually LeveLupik backend systems are already ready to process such requests.
But on Front it is waiting for the Drag and Drops animation implementation.

Planned at the next releases.

**Comment by ViktoriaNeva** [comment]
@levelupik 
Great! Than I’ll test it from the backend

**Comment by levelupik** [comment]
Done at v0.11.0.
