### ISSUE TITLE
Send me an invitation, please

### ISSUE THREAD

**Issue by D-Pav** [levelupik/levelupik#26]
Hello,
Please send me an invitation, I'd like to participate in the project as QA

**Comment by levelupik** [comment]
Hello @D-Pav !

Thank you for your interest in the Project.
Here is your invitation code:
`flyj;yE.euqq3LEWh5xSBtB?.gpWJxVMP9`

You can use it on https://finalem.levelupik.com
The current developing page is https://finalem.levelupik.com/display

**Comment by D-Pav** [comment]
Thank you
