### ISSUE TITLE
Just missed "is" in the error message

### ISSUE THREAD

**Issue by ViktoriaNeva** [levelupik/levelupik#27]
![2020-05-25_23-46-43](https://user-images.githubusercontent.com/5111608/82842553-acf8b780-9ee2-11ea-98cd-044c0ea6d8eb.png)

**Comment by levelupik** [comment]
Oh, you are already got at the reverse engineering point.
Such a great to hear.

Thank you for this error, the fix will be added in the next release.

**Comment by levelupik** [comment]
It is already have been fixed.
Thank you for this issue.
