### ISSUE TITLE
Text does not saved if past it without manual changes

### ISSUE THREAD

**Issue by ViktoriaNeva** [levelupik/levelupik#28]
Steps to Reproduce:
1. Create note
2. Copy some text:
Please, copy me. I am a good text
3. Past it in the created note - DO NOT do any changes with the note 
4. Change active note or reload the page

Actual Result:
Note doesn’t saved

Expected Result:
Note saved

**Comment by levelupik** [comment]
Thank you, actual stuff.

Will be fixed in the next releases.

**Comment by levelupik** [comment]
Can you check it is again, please?

It looks like a duplicate of https://github.com/levelupik/levelupik/issues/20
At the current version v0.2.1 text is saving by Steps:
1)) Go to `/display` page.
2)) Chose existed or a new category.
3)) Chose existed note
4)) Set cursor on body block
5)) `CTRL+V`(`Cmd+V`)
6)) Go to another category
7)) Go back to note on step 3.

Current:
The inserted text will be saved.

But if on step 3 create a new note and quick(less then 2 seconds) select body block(It is can be made by `TAB`), then `CTRL+V`(`Cmd+V`) and go to another category - inserted text will be not saved.
It is the same result as you have described in https://github.com/levelupik/levelupik/issues/20.
And the same bug.

**Comment by ViktoriaNeva** [comment]
@levelupik It's true. Bug is not reproducible anymore

But I don't think that this is a duplicate of the #20 
In this case pasted text wasn't saved, no matter how much time has been passed.
While in the #20 user should do reloading page or change active category/note really fast.

**Comment by levelupik** [comment]
Got it, thank you for feedback.
