### ISSUE TITLE
I need some more codes for testing registration

### ISSUE THREAD

**Issue by ViktoriaNeva** [levelupik/levelupik#34]
1. Test is there any error messages on console 
2. Register with api
3. Register with existing name and behavior of the system

It will be enough 5 codes (three for cases and two for unexpected situations)

**Comment by levelupik** [comment]
Okay, @ViktoriaNeva - it looks like it needs to make a code generator for the QA users.
For automatization reasons, it will be more comfortable and faster to get a new one from some technical page on the project.
Need to think about it, but for now `maybe possibly testing without codes`?

**Comment by ViktoriaNeva** [comment]
Sure. It is possible and enough work to do

**Comment by levelupik** [comment]
Great, thank you.
