### ISSUE TITLE
Keyboard "Enter" does not work for login

### ISSUE THREAD

**Issue by ViktoriaNeva** [levelupik/levelupik#4]
User must click by mouse on the login button on the screen. Will be more comfortable to use keyboard"Enter"

**Comment by levelupik** [comment]
You have a good speed of suggestions for improvements.
This improvement planned in the first iteration of the developing, but after the base functionality was planned to make a Display program firstly.

After your suggestion, it will be replanned and added in the next iterations.

**Comment by levelupik** [comment]
Thank you for your request.
Have been improved in a minor update.
