### ISSUE TITLE
No redirect to home page after log out

### ISSUE THREAD

**Issue by ViktoriaNeva** [levelupik/levelupik#40]
Steps to Reproduce:
1. Log in to the LL
2. Go to page /display
3. Log out on the page /display

Actual Result:
User still on the /display page
Categories which were opened in these session - can be opened after log out
![2020-07-28_02-02-55](https://user-images.githubusercontent.com/5111608/88600326-a15a7600-d076-11ea-9dbf-064a77c91b28.gif)
Expected Result:
User redirected on the LL's home page

**Comment by levelupik** [comment]
Great issue, it will be fixed in one of the next milestones.

**Comment by levelupik** [comment]
Redirection is implemented after `logout`.
