### ISSUE TITLE
Different background color for Title and Note's text

### ISSUE THREAD

**Issue by ViktoriaNeva** [levelupik/levelupik#46]
Steps to Reproduce:
1. Go to Notes
2. Create Note
3. Watch for the background colors for Title of the note and text

Actual Result:
Title background-color: #292929
Note's text  background-color: #282828

Expected Result:
Should be the same color

**Comment by levelupik** [comment]
Yeah, good point.
It will be fixed.

**Comment by levelupik** [comment]
Input for the note title was moved into note.
Now it is the same background color.
