### ISSUE TITLE
Wrong behaviour if click twice on editing

### ISSUE THREAD

**Issue by ViktoriaNeva** [levelupik/levelupik#49]
Environment:
Chrome
Version 87.0.4280.141
Safari
Version 14.0
FireFox
84.0.2 

Steps to Reproduce:
1. Click on the category
2. Click on the button "Edit"
3. Click on the button "Edit" again - case 1
4. Reload the page - case 2

Actual Result:
See video
https://user-images.githubusercontent.com/5111608/104506742-76e18280-55ee-11eb-87c4-0353b1412e36.mp4

case 1:
Note disappeared

case 2:
Note returned

Expected Result:
On the second click note just saved, for example

**Comment by ViktoriaNeva** [comment]
Addition for general bug

Steps to Reproduce:
1. Select category
2. Click on editing
3. Select another category
4. Click "Esc" on the keyboard - case 1
5. Click "Edit" - case 2

Actual Result:
https://user-images.githubusercontent.com/5111608/104508011-47cc1080-55f0-11eb-934b-c1ab01a7b574.mp4

case 1:
No reaction

case 2:
Disappeared selected in the first place category

After reloading all categories - ok

**Comment by levelupik** [comment]
Thank you, it is an important issue.
Will be fixed in the next release.

**Comment by levelupik** [comment]
You're additional comments:
>Click "Esc" on the keyboard - case 1

Need to investigate it.
This behavior potentially may have unexpected results, when you are working with the note and editing the category.
If the focus will be lost from category editing and added to the note, the application should understand to which element on the page need to apply the ESC click event.

**Comment by levelupik** [comment]
Double editing is fixed.
