### ISSUE TITLE
Text in the note if created new one

### ISSUE THREAD

**Issue by ViktoriaNeva** [levelupik/levelupik#9]
Steps to Reproduce:
1. Create new category
2. Create new note in the category
3. Write some text in the note
4. Click the button create new note

Actual Result:
Text from the previous note left
see screenshot 

Expected Result:
Empty fields
![2020-05-20_22-21-43](https://user-images.githubusercontent.com/5111608/82488536-b7810e80-9ae8-11ea-914f-b69ca1ee2823.png)

**Comment by levelupik** [comment]
Thank you!
It is a bad bug, in the caching system as I guess.

Sorry for that, it will be fixed in the next release.

**Comment by levelupik** [comment]
@ViktoriaNeva please, meet release v0.2.1 where this bug does not exist anymore.
